RxApp/Models/ApiModels/Author.cs
namespace RxApp.domain
{
    public class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int[] Books { get; set; }
    }
}

RxApp/Models/ApiModels/Book.cs
using Newtonsoft.Json;

namespace RxApp.domain
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public int Author { get; set; }
        
        [JsonIgnore]
        public string AuthorsName { get; set; }
    }
}

RxApp/Models/ControllerModels/AuthorControllerModel.cs
namespace RxApp.Models.ControllerModels
{
    public class AuthorControllerModel : BaseControllerModel
    {
        public class ById : AuthorControllerModel
        {
            public int Id { get; set; }
        }
        
        public class All : AuthorControllerModel
        {
            public string Name { get; set; }
        }
    }
}

RxApp/Models/ControllerModels/BaseControllerModel.cs
namespace RxApp.Models.ControllerModels
{
    public class BaseControllerModel
    {
        
    }
}

RxApp/Models/ControllerModels/BookControllerModel.cs
namespace RxApp.Models.ControllerModels
{
    public class BookControllerModel : BaseControllerModel
    {
        
        public class ById : BookControllerModel
        {
            public int Id { get; set; }
        }
        
        public class All : BookControllerModel
        {
            public string Title { get; set; }
            public double Year { get; set; }
        }
    }
}

RxApp/Models/ErrorViewModel.cs
using System;

namespace RxApp.Models
{
    public class ErrorViewModel
    {
        public string Message { get; set; }
        public Exception Exception { get; set; }

        public bool ShowMessage => !string.IsNullOrEmpty(Message);
    }
}

RxApp/Models/ViewModels/AuthorViewModel.cs
namespace RxApp.Models.ViewModels
{
    public class AuthorViewModel : BaseViewModel
    {
        public class Loading : AuthorViewModel
        { 
            
        }

        public class SetAuthor : AuthorViewModel
        {
            public int Id { get; private set; }
            public string Name { get; private set; }
        }    
    }
}

RxApp/Models/ViewModels/BaseViewModel.cs
namespace RxApp.Models.ViewModels
{
    public class BaseViewModel
    {
        
    }
}

RxApp/Models/ViewModels/BookViewModel.cs
using System;
using System.Collections.Generic;
using RxApp.domain;

namespace RxApp.Models.ViewModels
{
    public class BookViewModel : BaseViewModel
    {
        public class Loading : BookViewModel
        { 
            
        }

        public class SetBook : BookViewModel
        {
            public Book book { get; set; }
        }
        
        public class SetBooks : BookViewModel
        {
            public List<Book> books { get; set; }
        }
    }
}

RxApp/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;

namespace RxApp.Controllers
{
    [Route("/authors")]
    public class AuthorController : Controller
    {
        
    }
}

RxApp/Controllers/BooksController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RxApp.Models.ControllerModels;
using RxApp.ReactiveEventsManagers;
using RxApp.Service;

namespace RxApp.Controllers
{
    [Route("/books")]
    public class BooksController : Controller
    {
        private BooksEventManager _booksEventManager { get; }
        private IBookService _bookService { get; }


        public BooksController(BooksEventManager booksEventManager, IBookService bookService)
        {
            _booksEventManager = booksEventManager;
            _bookService = bookService;
        }


        public async Task<IActionResult> Books()
        {
            var sw = new Stopwatch();

            GCReset();
            sw.Restart();

            BookControllerModel controllerModel = new BookControllerModel.All();

            var msg = await _booksEventManager.GetStream(controllerModel);

            sw.Stop();
            Console.WriteLine("FromAsync: {0}", sw.ElapsedMilliseconds);

            GCReset();
            sw.Restart();

            ViewData["AllBooks"] = msg;
            return View();
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Book(int id)
        {
            var sw = new Stopwatch();

            GCReset();
            sw.Restart();

            BookControllerModel controllerModel = new BookControllerModel.ById {Id = id};

            var msg = await _booksEventManager.GetStream(controllerModel);

            sw.Stop();
            Console.WriteLine("FromAsync: {0}", sw.ElapsedMilliseconds);

            GCReset();
            sw.Restart();

            ViewData["Message"] = msg;
            return View();
        }

        private static void GCReset()
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }
    }
}

RxApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RxApp.Models;

namespace RxApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel());
        }
    }
}

RxApp/Views/Books/Book.cshtml
@{
    ViewData["Title"] = "Book Page";
}

<div class="row">
    <div class="col-md-3">
        <h2>@ViewBag.Message.book.Title</h2>

        @{
            var data = ViewBag.Message.book;
        }
        <h4>Id: @data.Id</h4>
        <h4>First published: @data.Year</h4>
        <h4>Author: @data.AuthorsName</h4>

    </div>
</div>

RxApp/Views/Books/Books.cshtml
@using RxApp.Models

@{
    ViewData["Title"] = "Books Page";
    
}

<div class="row">
    <div class="col-md-3">
        <h2>All Books</h2>
        <ul>
             @foreach (var book in ViewBag.AllBooks.books)
             {
                 <li>
                     <a href="/books/@book.Id">
                         <span class="text-primary">@book.Title, @book.Year</span>
                     </a>
                 </li>
            }
        </ul>
        
    </div>
</div>

RxApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

RxApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RxApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    @* <div class="col-md-3"> *@
    @*     <h2>Application uses</h2> *@
    @*     <ul> *@
    @*         <li>Sample pages using ASP.NET Core MVC</li> *@
    @*         <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li> *@
    @*     </ul> *@
    @* </div> *@
    <div class="col-md-3">
        <h2>RX intro</h2>
        <ul>
            <li><a href="http://reactivex.io/">Official docs</a></li>
            <li><a href="http://introtorx.com/">Introduction to Rx</a></li>
            <li><a href="https://leecampbell.com/2010/08/25/reactive-extensions-for-net-an-introduction/">Reactive Extensions for .NET</a></li>
            <li><a href="https://channel9.msdn.com/Tags/reactive+extensions">Channel 9 MSDN videos</a></li>
        </ul>
    </div>
    @* <div class="col-md-3"> *@
    @*     <h2>Overview</h2> *@
    @*     <ul> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li> *@
    @*     </ul> *@
    @* </div> *@
    @* <div class="col-md-3"> *@
    @*     <h2>Run &amp; Deploy</h2> *@
    @*     <ul> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li> *@
    @*         <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li> *@
    @*     </ul> *@
    @* </div> *@
</div>

RxApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RxApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RxApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Books" asp-action="Books">Books</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - RxApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>